In [2]:
from pathlib import Path
import ast
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import wfdb

from IPython.display import display

warnings.filterwarnings("ignore", category=FutureWarning)

In [3]:


DATA_DIR = Path.cwd().parent/ "data"

METADATA_FILE = DATA_DIR / "ptbxl_database.csv"
STATEMENTS_FILE = DATA_DIR / "scp_statements.csv"

print("Dataset directory:", DATA_DIR)
print("Metadata exists:", METADATA_FILE.exists())
print("Diagnostic statements exist:", STATEMENTS_FILE.exists())

Dataset directory: C:\Users\pmondal\Documents\CardioTrustAI\src\CardioTrustAI.Backend\CardioTrustAI.PythonAPI\data
Metadata exists: True
Diagnostic statements exist: True

In [4]:

df = pd.read_csv(METADATA_FILE)
scp = pd.read_csv(STATEMENTS_FILE, index_col=0)

,description,diagnostic,form,rhythm,diagnostic_class,diagnostic_subclass,Statement Category,SCP-ECG Statement Description,AHA code,aECG REFID,CDISC Code,DICOM Code
NDT,non-diagnostic T abnormalities,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,non-diagnostic T abnormalities,NaN,NaN,NaN,NaN
NST_,non-specific ST changes,1.0,1.0,NaN,STTC,NST_,Basic roots for coding ST-T changes and abnorm...,non-specific ST changes,145.0,MDC_ECG_RHY_STHILOST,NaN,NaN
DIG,digitalis-effect,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,suggests digitalis-effect,205.0,NaN,NaN,NaN
LNGQT,long QT-interval,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,long QT-interval,148.0,NaN,NaN,NaN
NORM,normal ECG,1.0,NaN,NaN,NORM,NORM,Normal/abnormal,normal ECG,1.0,NaN,NaN,F-000B7
IMI,inferior myocardial infarction,1.0,NaN,NaN,MI,IMI,Myocardial Infarction,inferior myocardial infarction,161.0,NaN,NaN,NaN
ASMI,anteroseptal myocardial infarction,1.0,NaN,NaN,MI,AMI,Myocardial Infarction,anteroseptal myocardial infarction,165.0,NaN,NaN,NaN
LVH,left ventricular hypertrophy,1.0,NaN,NaN,HYP,LVH,Ventricular Hypertrophy,left ventricular hypertrophy,142.0,NaN,C71076,NaN
LAFB,left anterior fascicular block,1.0,NaN,NaN,CD,LAFB/LPFB,Intraventricular and intra-atrial Conduction d...,left anterior fascicular block,101.0,MDC_ECG_BEAT_BLK_ANT_L_HEMI,C62267,D3-33140
ISC_,non-specific ischemic,1.0,NaN,NaN,STTC,ISC_,Basic roots for coding ST-T changes and abnorm...,ischemic ST-T changes,226.0,NaN,NaN,NaN

In [22]:
print("Total ECG records:", len(df))
print("Unique patients:", df["patient_id"].nunique())

Total ECG records: 21799
Unique patients: 18869

In [23]:
display(df.head(10))

,ecg_id,patient_id,age,sex,height,weight,nurse,site,device,recording_date,...,validated_by_human,baseline_drift,static_noise,burst_noise,electrodes_problems,extra_beats,pacemaker,strat_fold,filename_lr,filename_hr
0,1,15709.0,56.0,1,NaN,63.0,2.0,0.0,CS-12 E,1984-11-09 09:17:34,...,True,NaN,", I-V1,",NaN,NaN,NaN,NaN,3,records100/00000/00001_lr,records500/00000/00001_hr
1,2,13243.0,19.0,0,NaN,70.0,2.0,0.0,CS-12 E,1984-11-14 12:55:37,...,True,NaN,NaN,NaN,NaN,NaN,NaN,2,records100/00000/00002_lr,records500/00000/00002_hr
2,3,20372.0,37.0,1,NaN,69.0,2.0,0.0,CS-12 E,1984-11-15 12:49:10,...,True,NaN,NaN,NaN,NaN,NaN,NaN,5,records100/00000/00003_lr,records500/00000/00003_hr
3,4,17014.0,24.0,0,NaN,82.0,2.0,0.0,CS-12 E,1984-11-15 13:44:57,...,True,", II,III,AVF",NaN,NaN,NaN,NaN,NaN,3,records100/00000/00004_lr,records500/00000/00004_hr
4,5,17448.0,19.0,1,NaN,70.0,2.0,0.0,CS-12 E,1984-11-17 10:43:15,...,True,", III,AVR,AVF",NaN,NaN,NaN,NaN,NaN,4,records100/00000/00005_lr,records500/00000/00005_hr
5,6,19005.0,18.0,1,NaN,58.0,2.0,0.0,CS-12 E,1984-11-28 13:32:13,...,True,", V1",NaN,NaN,NaN,NaN,NaN,4,records100/00000/00006_lr,records500/00000/00006_hr
6,7,16193.0,54.0,0,NaN,83.0,2.0,0.0,CS-12 E,1984-11-28 13:32:22,...,True,NaN,NaN,NaN,NaN,NaN,NaN,7,records100/00000/00007_lr,records500/00000/00007_hr
7,8,11275.0,48.0,0,NaN,95.0,2.0,0.0,CS-12 E,1984-12-01 14:49:52,...,True,", II,AVF",", I-AVF,",NaN,NaN,NaN,NaN,9,records100/00000/00008_lr,records500/00000/00008_hr
8,9,18792.0,55.0,0,NaN,70.0,2.0,0.0,CS-12 E,1984-12-08 09:44:43,...,True,NaN,", I-AVR,",NaN,NaN,NaN,NaN,10,records100/00000/00009_lr,records500/00000/00009_hr
9,10,9456.0,22.0,1,NaN,56.0,2.0,0.0,CS-12 E,1984-12-12 14:12:46,...,True,NaN,NaN,NaN,NaN,NaN,NaN,9,records100/00000/00010_lr,records500/00000/00010_hr

In [24]:
print(df.columns.tolist())

['ecg_id', 'patient_id', 'age', 'sex', 'height', 'weight', 'nurse', 'site', 'device', 'recording_date', 'report', 'scp_codes', 'heart_axis', 'infarction_stadium1', 'infarction_stadium2', 'validated_by', 'second_opinion', 'initial_autogenerated_report', 'validated_by_human', 'baseline_drift', 'static_noise', 'burst_noise', 'electrodes_problems', 'extra_beats', 'pacemaker', 'strat_fold', 'filename_lr', 'filename_hr']

In [25]:
print(scp["diagnostic_class"].value_counts(dropna=False))

diagnostic_class
NaN     27
MI      14
STTC    13
CD      11
HYP      5
NORM     1
Name: count, dtype: int64

In [5]:
print(scp[["description", "diagnostic", "diagnostic_class"]].head(20))

                                               description  diagnostic  \
NDT                         non-diagnostic T abnormalities         1.0
NST_                               non-specific ST changes         1.0
DIG                                       digitalis-effect         1.0
LNGQT                                     long QT-interval         1.0
NORM                                            normal ECG         1.0
IMI                         inferior myocardial infarction         1.0
ASMI                    anteroseptal myocardial infarction         1.0
LVH                           left ventricular hypertrophy         1.0
LAFB                        left anterior fascicular block         1.0
ISC_                                 non-specific ischemic         1.0
IRBBB                 incomplete right bundle branch block         1.0
1AVB                                 first degree AV block         1.0
IVCD     non-specific intraventricular conduction distu...         1.0
ISCAL                      ischemic in anterolateral leads         1.0
CRBBB                   complete right bundle branch block         1.0
CLBBB                    complete left bundle branch block         1.0
ILMI                   inferolateral myocardial infarction         1.0
LAO/LAE                   left atrial overload/enlargement         1.0
AMI                         anterior myocardial infarction         1.0
ALMI                   anterolateral myocardial infarction         1.0

        diagnostic_class
NDT                 STTC
NST_                STTC
DIG                 STTC
LNGQT               STTC
NORM                NORM
IMI                   MI
ASMI                  MI
LVH                  HYP
LAFB                  CD
ISC_                STTC
IRBBB                 CD
1AVB                  CD
IVCD                  CD
ISCAL               STTC
CRBBB                 CD
CLBBB                 CD
ILMI                  MI
LAO/LAE              HYP
AMI                   MI
ALMI                  MI

In [7]:
diagnostic_classes = scp[
    scp["diagnostic"] == 1
]["diagnostic_class"].value_counts(dropna=False)

In [10]:
print(diagnostic_classes)

diagnostic_class
MI      14
STTC    13
CD      11
HYP      5
NORM     1
Name: count, dtype: int64

In [11]:
print(df[["ecg_id", "patient_id", "age", "sex", "scp_codes"]].head(10))

   ecg_id  patient_id   age  sex                                 scp_codes
0       1     15709.0  56.0    1  {'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}
1       2     13243.0  19.0    0              {'NORM': 80.0, 'SBRAD': 0.0}
2       3     20372.0  37.0    1                {'NORM': 100.0, 'SR': 0.0}
3       4     17014.0  24.0    0                {'NORM': 100.0, 'SR': 0.0}
4       5     17448.0  19.0    1                {'NORM': 100.0, 'SR': 0.0}
5       6     19005.0  18.0    1                {'NORM': 100.0, 'SR': 0.0}
6       7     16193.0  54.0    0                {'NORM': 100.0, 'SR': 0.0}
7       8     11275.0  48.0    0    {'IMI': 35.0, 'ABQRS': 0.0, 'SR': 0.0}
8       9     18792.0  55.0    0                {'NORM': 100.0, 'SR': 0.0}
9      10      9456.0  22.0    1                {'NORM': 100.0, 'SR': 0.0}